version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  reviewers:
  - julienduchesne
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.31
    - 1.37.1
    - 1.37.10
    - 1.37.15
    - 1.37.20
    - 1.37.25
    - 1.37.6
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.8.0
