# Build customization
builds:
  - binary: credentials-sync
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: zip

  replacements:
    amd64: 64-bits
    darwin: macOS

  files:
    - nothing.*

# GitHub release customization
release:
  draft: true
  prerelease: true
