# Build customization
builds:
  - binary: credentials-sync
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archives:
  - format: zip

    files:
      - nothing.*

# GitHub release customization
release:
  draft: true
  prerelease: "true"
