language: go

go: "1.12.x"

env:
  - GO111MODULE=on CGO_ENABLED=0

install:
  - go build

script:
  - bash ./test.sh
  - bash <(curl -s https://codecov.io/bash)
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      curl -sL https://git.io/goreleaser | bash;
    fi