name: Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.26
        id: go

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v

      - name: Run Tests
        run: |
          bash ./test.sh

# note: codecov action is disallowed per organization policy
#      - name: Upload to codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.txt
#          fail_ci_if_error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker build . -t ghcr.io/coveooss/credentials-sync:latest
          docker push ghcr.io/coveooss/credentials-sync:latest

      - name: Build Tag
        if: github.ref != 'refs/heads/main'
        run: |
          export tag=$(cut -d'/' -f3 <<<'${{ github.ref }}')
          docker build . -t ghcr.io/coveooss/credentials-sync:$tag
          docker push ghcr.io/coveooss/credentials-sync:$tag

      - name: Push release
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
