name: Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.21
        id: go

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v

      - name: Run Tests
        run: |
          bash ./test.sh

# note: codecov action is disallowed per organization policy
#      - name: Upload to codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.txt
#          fail_ci_if_error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker build . -t ghcr.io/coveooss/credentials-sync:latest
          docker push ghcr.io/coveooss/credentials-sync:latest

      - name: Build Tag
        if: github.ref != 'refs/heads/main'
        run: |
          export tag=$(cut -d'/' -f3 <<<'${{ github.ref }}')
          docker build . -t ghcr.io/coveooss/credentials-sync:$tag
          docker push ghcr.io/coveooss/credentials-sync:$tag

      - name: Push release
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
