name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v

      - name: Run Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash ./test.sh
          bash <(curl -s https://codecov.io/bash)

      - name: Docker Login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build Latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker build . -t coveo/credentials-sync:latest
          docker push coveo/credentials-sync:latest

      - name: Build Tag
        if: github.ref != 'refs/heads/master'
        run: |
          export tag=$(cut -d'/' -f3 <<<'${{ github.ref }}')
          docker build . -t coveo/credentials-sync:$tag
          docker push coveo/credentials-sync:$tag

      - name: Push release
        if: github.ref != 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
