name: Build
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.27
        id: go

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v

      - name: Run Tests
        run: |
          bash ./test.sh

# note: codecov action is disallowed per organization policy
#      - name: Upload to codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.txt
#          fail_ci_if_error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker build . -t ghcr.io/coveooss/credentials-sync:latest
          docker push ghcr.io/coveooss/credentials-sync:latest

      - name: Build Tag
        if: github.ref != 'refs/heads/main'
        run: |
          export tag=$(cut -d'/' -f3 <<<'${{ github.ref }}')
          docker build . -t ghcr.io/coveooss/credentials-sync:$tag
          docker push ghcr.io/coveooss/credentials-sync:$tag

      - name: Push release
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
